const data = [
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
  {
    lecturerName: "Smith",
    courseName: "CPITA",
    batchCode: "CPITA/K/68",
    paymentMonth: "2023-04",
    totalHours: "40h, 0m",
    paymentRate: "Hourly Rate",
    payAmount: 10150,
  },
];

export default data;
