const data = [
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
  {
    lecturerNic: "199535162140",
    lecturerName: "Asha Madushani",
    courseName: "OOC (L) WEnd",
    batchCode: "OOC(Lab)-Asha-July 2023(Weekend)",
    payRate: "Hourly Rate",
    totalHours: "30h : 0m",
    remainingHours: "4h : 0m",
  },
];

export default data;
